### PR TITLE
Add missing iterator header.

### PR DESCRIPTION
**Pull request by hzeller**

### CODE REVIEW

**Comment by hzeller** [comment]
The CI failures seem unrelated.

**Comment by vaughnbetz** [comment]
Re-launching CI to see if these failures were some transient issue. The failures are:
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-biqc8nbg/black

**Comment by vaughnbetz** [comment]
Launching CI again since Alireza fixed the infrastructure issue.

**Comment by vaughnbetz** [comment]
@hzeller @sdamghan @alirezazd : any idea why this (very safe) change is still failing with the python black module infrastructure issue?  I've relaunched CI since Alireza's infrastructure fix -- I would have thought that was enough for it to pass CI.  Am I missing something, or is the infrastructure perhaps persisting?

**Comment by sdamghan** [comment]
I believe this branch needs to be rebased with the VTR master branch, and then we can check the CI tests. I see in Henner's repository that this branch is two commits behind the VTR master branch.

**Comment by hzeller** [comment]
Rebased it now, let's see what the Ci thinks.

**Comment by hzeller** [comment]
Alright, looks like it is ready to merge!

**Pull request merged**
