### PR TITLE
Adding documentation for the mapping between atom and clustered netlist

### PR DESCRIPTION
**Pull request by MohamedElgammal**
In this PR, I am adding some documentation under VPR API section of the docs to explain how we can map between the atom and clustered netlists.

#### Checklist:

- [ ] My change requires a change to the documentation
- [x ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by MohamedElgammal** [comment]
@SebastianLievano This might be useful for you. You can take a look at it here until it's landed.

**Comment by MohamedElgammal** [comment]
@SebastianLievano This might be useful for you. You can take a look at it here until it's landed.

**Review by vaughnbetz — APPROVED** [review]
Looks good.
Some small grammatical tweaks.
Not sure if it is best to write .rst files directly like this or generate from Doxygen. Doxygen keeps the documentation with the code, but may be less readable than these nice summaries. Let me know what you think.

**Comment by MohamedElgammal** [comment]
Thanks for the review. I just thought that writing the rst file directly will allow me to group the documentation of all the functions used to map between the clustered and atom netlists especially since these functions are scattered in different classes (AtomLookup, ClusteredAtomsLookup, and the re_cluster_util.h file.

**Comment by MohamedElgammal** [comment]
I have just fixed the grammatical issues and will merge once the "required" tests are done.

**Pull request merged**
