### PR TITLE
Add missed contents of source identifiers into local ones

### PR DESCRIPTION
**Pull request by sdamghan**
Support signed values for arithmetic shift

Odin does not completely support **signed** values yet. As already the implementation of arithmetic shift operation has been done completely, a solution is proposed to have the signed values shift operation support.

#### Description

This commit resolves the missed hierarchical contents for IDENTIFIERs. Odin creates a new IDENTIFIER ast_node when faces global or local variable usage. However, critical information like variable _signedness_ is not transferred to the new node. So, the added code addresses this problem when Odin reduces expressions. 

#### Related Issue

Commits #1560 and #1468
Issue #38

#### How Has This Been Tested?

    1. make test (ODIN-II)
    2. Basic Regression Tests
    3. Strong Regression Test
    4. Basic Valgrind Memory Tests (also, Valgrind memory tests for all other regression suits)
    5. Sanitized Basic Regression Tests
    6. Odin-II Micro Tests

#### Types of changes

- [x] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by sdamghan** [comment]
Hi @vaughnbetz ,
I see an unsuccessful check for this PR related to the VTR weekly test; however, the build log files ([link](https://source.cloud.google.com/results/invocations/a7b86037-fe11-4c73-a983-86754aac5418/artifacts/)) under the artifact tab are empty! Would you please let me know how I can find the errors log?

**Comment by vaughnbetz** [comment]
I'm not sure.  I see only green (all tests passed) under this PR when I click on checks, so I'm not sure what error you're referring to.

**Comment by sdamghan** [comment]
I referred to the red cross mark for my last commit (Merge pull request #1633 ...) in the master branch. It shows an unsuccessful check for the VtR Weekly Test!

**Comment by vaughnbetz** [comment]
Ah, I see, thanks.  I'm not sure what happened; the log is empty as far as I can see too.  I know the CI system has been modified a lot recently to move to github actions.  @litghost: any idea, and do you think this is a real issue that needs investigation?

**Pull request merged**
