### PR TITLE
Documentation changes and grammatical/spelling corrections

### PR DESCRIPTION
**Pull request by harpreetbamrah**
#### Description
Grammatical/spelling corrections and name addition to contributors

#### Related Issue
None

#### Motivation and Context
Fix typos

#### How Has This Been Tested?
Not required as no changes to the code base

#### Types of changes

- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [x] My change requires a change to the documentation
- [x] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by sdamghan** [comment]
@harpreetbamrah would you please update your branch? it is much better and cleaner to have one commit merged to the master branch. thanks

**Comment by harpreetbamrah** [comment]
> @harpreetbamrah would you please update your branch? it is much better and cleaner to have one commit merged to the master branch. thanks

I actually did that intentionally for seggregation, anyhow merged into single commit and good to go now, thanks.

**Comment by harpreetbamrah** [comment]
@sdamghan this is ready to be merged, thanks.

**Comment by sdamghan** [comment]
Thanks @harpreetbamrah it looks good,
@vaughnbetz if it looks good in your opinion It can be merged.

**Comment by harpreetbamrah** [comment]
@sdamghan @vaughnbetz I can update the branch before merge when it's all good from your end, thanks!

**Comment by vaughnbetz** [comment]
Looks good -- thanks Harpreet.

**Pull request merged**
