### PR TITLE
Faster log parsing: fix parse_vtr_flow.py to only read each log file once

### LINKED ISSUE #1647: Very long runtime in parse_vtr_flow
```
  %Own   %Total  OwnTime  TotalTime  Function (filename:line)                                                                                                                                                                                                                             
 51.00%  58.00%    6.26s     7.17s   parse_vtr_flow (vtr/parse_vtr_flow.py:75)
 26.00%  26.00%    2.59s     2.59s   parse_vtr_flow (vtr/parse_vtr_flow.py:72)
 14.00%  14.00%    1.04s     1.04s   parse_vtr_flow (vtr/parse_vtr_flow.py:73)
  7.00%   7.00%   0.810s    0.810s   regex (vtr/inspect.py:39)
  2.00%   2.00%   0.150s    0.150s   parse_vtr_flow (vtr/parse_vtr_flow.py:76)
  0.00%   0.00%   0.100s    0.100s   regex (vtr/inspect.py:37)
  0.00%   0.00%   0.050s    0.050s   parse_vtr_flow (vtr/parse_vtr_flow.py:74)
  0.00% 100.00%   0.000s    11.00s   parse_task (vtr/parse_vtr_task.py:207)
  0.00% 100.00%   0.000s    11.00s   run_tasks (run_reg_test.py:315)
  0.00% 100.00%   0.000s    11.00s   <module> (run_reg_test.py:342)
  0.00% 100.00%   0.000s    11.00s   vtr_command_main (run_vtr_task.py:246)
  0.00% 100.00%   0.000s    11.00s   run_tasks (run_vtr_task.py:297)
  0.00% 100.00%   0.000s    11.00s   parse_tasks (vtr/parse_vtr_task.py:186)
  0.00% 100.00%   0.000s    11.00s   vtr_command_main (run_reg_test.py:183)

```

### PR DESCRIPTION
**Pull request by jgoeders**
#### Related Issue
Closes #1647 

#### Types of changes

- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by vaughnbetz** [comment]
The failures in vtr_reg_nightly are due to QoR improving on a few circuits:
arm_core has significantly fewer RAMs, which is making area/resource count QoR too good to pass. @sdamghan : I think your recent changes improved memory QoR: was arm_core a big win?  If so we need new golden results?
That's 16 faiures.
The last one is in Titan, and is a worst-negative slack that got a lot better.  Jeff can you double check that wns was parsed correctly?  If so we can merge this.
stratixiv_arch.timing.xml/minres_stratixiv_arch_timing.blif/common setup_WNS relative value 1.4499921074291642 outside of range [0.5,1.4] and not equal to golden value: -7.09528

**Comment by jgoeders** [comment]
@vaughnbetz

When I run `stratixiv_arch.timing.xml/minres_stratixiv_arch_timing.blif` locally on this branch I'm seeing `Final setup Worst Negative Slack (sWNS): -8.91171 ns` in the log, which is also what the parser is extracting, and within the QoR range. 

If I understand how the golden works, the relative value the nightly found (1.4499921074291642) and golden (-7.09528), would mean a WNS of -10.288, which seems like a large increase, and not matching what I found locally. 

It's running again now, but I'll investigate some more.

**Comment by jgoeders** [comment]
I ran the full vtr_reg_nightly locally and indeed I get:
`Final setup Worst Negative Slack (sWNS): -10.2881 ns`

So it is parsing it correctly.  

I'm not sure why I got different results when trying to run the individual design on it's own, although I seemed to have missed the `--initial_pres_fac 1.0 --router_profiler_astar_fac 1.5` configuration that this circuit is run with in the regression test so that's probably the reason.

**Comment by jgoeders** [comment]
@vaughnbetz , since it seems like the parsing is working fine, I'm going to merge this.

**Pull request merged**
