### PR TITLE
Initializing defined_size in VNumber Copy constructor

### PR DESCRIPTION
**Pull request by sdamghan**
Signed-off-by: Seyed Alireza Damghani <sdamghan@unb.ca>

#### Description

In VNumber copy constructor with new length, the defined_size variable was not initialized. As a result, Odin_II would throw an error in case of facing new VNumbers without defined_size equal to true while they have already a size specified.  

#### Related Issue

#1738

#### Motivation and Context

Bug fix!

#### Types of changes

- [x] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by sdamghan** [comment]
@ArashAhmadian Thanks for finding the bug!
This PR would fix the last issue you mentioned in the email. Waiting for CI green checkmarks then will be merged.
Please let me know your thoughts.

**Comment by ArashAhmadian** [comment]
@sdamghan Great! Thanks for letting me know.

**Comment by sdamghan** [comment]
@vaughnbetz This PR is ready to merge as well.

**Comment by ArashAhmadian** [comment]
@vaughnbetz Could you merge this PR?

**Comment by vaughnbetz** [comment]
I'm going to let CI keep going overnight as I want to see if vtr_nightly_reg works this time (indicating it was a transient kokoro issue).  Will merge tomorrow morning.

**Comment by ArashAhmadian** [comment]
> I'm going to let CI keep going overnight as I want to see if vtr_nightly_reg works this time (indicating it was a transient kokoro issue). Will merge tomorrow morning.

Sounds good.

**Comment by vaughnbetz** [comment]
All CI passed, so the kokoro failure was transient.

**Comment by sdamghan** [comment]
Awesome, thanks @vaughnbetz

**Pull request merged**
