### PR TITLE
Fix build errors with VERBOSE

### PR DESCRIPTION
**Pull request by mkurc-ant**
This PR contains some general fixes

#### Description
The PR fixes build errors when `VERBOSE` is defined. It also fixes VPR ignoring netlist verbosity commandline option.

#### Motivation and Context

The need for debugging

#### How Has This Been Tested?

Locally, and hopefully in the CI

#### Types of changes

- [x] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by mithro** [comment]
@mkurc-ant - We should make sure that this is checked in CI somewhere?

**Comment by vaughnbetz** [comment]
Thanks. Changes look good, but need a make format to pass CI.

**Comment by mkurc-ant** [comment]
Sure. I'll add a CI test to check compilation with VERBOSE enabled + do code formatting.

**Comment by vaughnbetz** [comment]
Sorry, didn't merge this fast enough and it has conflict now. Can you resolve them and ping me @mkurc-ant ?

**Review by vaughnbetz — APPROVED** [review]
Code changes look good to me; just need to resolve a conflict.

**Comment by mkurc-ant** [comment]
Hi @vaughnbetz, I've resolved the conflict and rebased this PR on the current master.

**Pull request merged**
