### PR TITLE
[Odin]: Sorting the instance ports based on the related module, function or task

### PR DESCRIPTION
**Pull request by sdamghan**
#### Description

Previously, the simple swap of two items at a time has been used as the sort approach for instance port connection, to reorder them according to the main module (function or task) that they are instantiated from. That would cause an error since we alter the array of ports each time, which results in an unexpected change in the array for future swapping. The new approach uses a helper array to order the ports and then reorder the instantiated instance ports.

#### Related Issue

 #1699

#### Motivation and Context

bug fix

#### How Has This Been Tested?

1. make test (ODIN-II)
2. Basic Regression Tests
3. Strong Regression Test
4. Basic Valgrind Memory Tests (also, Valgrind memory tests for all other regression suits)
5. Sanitized Basic Regression Tests
6. Odin-II Micro Tests

#### Types of changes

- [x] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by sdamghan** [comment]
@aman26kbm and @dlrauch15
The bug was related to using a simple swap at a time for re-ordering instance ports. So, by swapping two ports each time, the main array was altered, and afterwards, the array was not valid for the previously achieved indexes for swapping. I have provided the solution in this PR.  
The provided test case in the issue is passed. Would you please have it confirmed based on the other failure cases? 

Please let me know if you have any thoughts about the code as well.

**Comment by sdamghan** [comment]
@vaughnbetz this is ready for merge, please let me know your thoughts :)

**Comment by vaughnbetz** [comment]
@sdamghan: Looks good. Thanks for the new commenting.
If no automatic test caught this, could one be created and added to the CI regtests?

**Comment by sdamghan** [comment]
> @sdamghan: Looks good. Thanks for the new commenting.
> If no automatic test caught this, could one be created and added to the CI regtests?
@vaughnbetz 
Yes, for sure. I'll add an appropriate test to regtests.

**Pull request merged**
