### PR TITLE
Add a new API partition_edges() to RRGraphBuilder

### PR DESCRIPTION
**Pull request by hariszafar-lm**
**Description**
This PR focuses on updating routing resource graph builder functions, where we use the refactored data structure `RRGraphBuilder` to shadow the discrete data structure `rr_graph_storage`.
This PR aims to fully refactored/deprecate the direct use of the legacy API `partition_edges()` from the `rr_node` data structure.

After this PR, the `partition_edges()` from the refactored data structure `RRGraphBuilder` is the only way to use it.

**Checklist:**
- [x]  Removed the legacy API `partition_edges()` from `rr_node.cpp` and `rr_node.h` (if present)
- [x]  Added new API `partition_edges()` to data structures `RRGraphBuilder`, whose comments are Doxygen compatible
- [x]  Replaced all the use of `partition_edges()` in respective functions (if needed)

**Related Issue**
This pull request is a follow-up PR on the routing resource graph refactoring effort #1805, #1868

**Motivation and Context**
This PR is a continuation of the refactoring effort with a focus on shadowing the `rr_graph_storage` APIs in the `RRGraphBuilder` data structure.
This PR refactored the `partition_edges()` API among the other APIs in #1847, #1868

**How Has This Been Tested?**
- [x]  All vtr basic and strong tests are passing.

**Types of changes**
- [x]  Bug fix (change which fixes an issue)
- [ ]  New feature (change which adds functionality)
- [ ]  Breaking change (fix or feature that would cause existing functionality to change)

**Checklist:**
- [ ]  My change requires a change to the documentation
- [x]  I have updated the documentation accordingly
- [ ]  I have added tests to cover my changes
- [ ]  All new and existing tests passed

### CODE REVIEW

**Comment by tangxifan** [comment]
@hariszafar-lm Just need to resolve the conflicts. We are good to go.

**Comment by hariszafar-lm** [comment]
VtR Nightly test 1 is passing locally. Don't know why it's failing here.

**Comment by tangxifan** [comment]
> VtR Nightly test 1 is passing locally. Don't know why it's failing here.

No worries. I will restart it. It is mainly due to some glitches in servers.

**Comment by tangxifan** [comment]
@hariszafar-lm Just resolve the merging conflicts. We can merge now.

**Pull request merged**
