### PR TITLE
ODIN_MEMLEAK: freed unused pin names

### PR DESCRIPTION
**Pull request by ademmings**
#### Motivation and Context
memory leaks in odin

#### How Has This Been Tested?
odin pre_commit regression suite

#### Types of changes
- [x] Bug fix (change which fixes an issue)

#### Checklist:
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by jeanlego** [comment]
I think this is unecessary since one of your recent PR properly cleans up nnode pin names now. could you verify?

**Comment by ademmings** [comment]
I did check this when I made the other PR, but just checked again anyway. These names don't get freed even with the new changes, and I think it's because the names get overwritten later on in this function. If I can figure out exactly where that is, I could move these frees to a better spot (they're in a bit of a weird place right now because I couldn't find a better one when I originally looked at this)

**Comment by jeanlego** [comment]
yeah, I'm not exactly sure i like it being there either. although it probably is correct, there could be other things not being freed. We could change this to WIP and explore deeper. Would you need help with this one ?

**Comment by jeanlego** [comment]
Did you need this merged for anything else? If so, this is not wrong per say, simply I don't like it there since it does not tell you were the name gets allocated being so far from the originating point.

**Comment by ademmings** [comment]
I actually just found exactly where it is! Going to clean it up and run the test to be sure.

**Comment by jeanlego** [comment]
good catch :)

**Pull request merged**
