### PR TITLE
Documentation Changes to CMakeLists.txt

### PR DESCRIPTION
**Pull request by georgkrylov**
This is a short commit that helps fixing the build breakage, with suggesting proper library.
Simplifies ease of use

Signed-off-by: Georgiy Krylov <georgiy.krylov@unb.ca>

#### Description

Since the changes mid-August, the build on the main branch would fail if libgtk-3.0-dev was failing.
The suggested to the CMake error message fix resolved it for me, while the original message was 
insufficient

#### How Has This Been Tested?

Building using the suggested library succeeded. Ubuntu 19.10
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~19.10) 

#### Types of changes

- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
N/A

#### Checklist:

- [ ] My change requires a change to the documentation
- [X] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [X] All new and existing tests passed

Since it is a "documentation" change, nothing should be affected.

### CODE REVIEW

**Comment by georgkrylov** [comment]
@jeanlego 
Can you please have a look at the changes. They might be helpful for other people who work on the main branch.

**Comment by jeanlego** [comment]
This is good with me

**Comment by vaughnbetz** [comment]
Looks good; thanks.

**Review by jeanlego — APPROVED** [review]

**Comment by vaughnbetz** [comment]
Waiting for vtr strong to run; something seems to be wrong with kokoro (multiple PRs are waiting for this).

**Comment by jeanlego** [comment]
> Waiting for vtr strong to run; something seems to be wrong with kokoro (multiple PRs are waiting for this).

Noticed that too. Any specific reason to also make Kokoro mandatory? I thought we were running strong on Travis alread

**Comment by vaughnbetz** [comment]
Sorry, misspoke: kokoro runs nightly tests (extra-strong!).  For this pr it won't make a difference; I'll need to mess around with permissions to force merge it.  If it stuck for a while I can do that.

**Comment by vaughnbetz** [comment]
Trying to force kokoro to re-run ...

**Comment by jeanlego** [comment]
> Trying to force kokoro to re-run ...

Thanks!
Is that in the docs? Otherwise I can add that in

**Pull request merged**
