### PR TITLE
Eblif write support

### PR DESCRIPTION
**Pull request by acomodi**
#### Description

This PR adds the feature to output `.param` and `.attr` to the `blif` file produced when the `--gen_post_synthesis_netlist` option is enabled.

#### Motivation and Context

This change is necessary to add additional information in the analysis of the post-synthesis netlist output.

#### How Has This Been Tested?

To test the correct functionality I have created a small regression test which in which the `--gen_post_synthesis_netlist` is enabled and the top.blif file is produced.

#### Types of changes

- [ ] Bug fix (change which fixes an issue)
- [x] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by mithro** [comment]
@acomodi - Ping? I think this is ready to be merged? Does it need some testing or something?

@vaughnbetz / @kmurray - Ping?

**Comment by acomodi** [comment]
@mithro I think it is ready to be merged, there is a regression test. It just needs to be reviewed.

**Comment by acomodi** [comment]
@mithro, @vaughnbetz, @kmurray - I have added the attribute write support as well which did not work. Now the PR is complete, ready to be reviewed.

**Comment by kmurray** [comment]
So it looks like this will only output the .attr/.param statements if those have been annotated in the input netlist, and it does not generate any .conn or .cname states. Is that correct?

This seems like a good choice since it means a standard BLIF file is generated unless .param/.attr were specified.

It is important that VPR remain capable of generating a standard BLIF since we load the generated BLIF into ABC to do formal verification, and ABC doesn't understand any of the new EBLIF statements.

**Comment by acomodi** [comment]
@kmurray Yes indeed, .attr and .params should be outputted only if they were present in the input netlist.

I could add another check in the test that does not have .param and .attr in the input netlist to make sure they are not outputted in the resulting blif

**Comment by kmurray** [comment]
Nope, sounds good as is -- just wanted to check my understanding.

**Comment by kmurray** [comment]
Thanks for the enhancement!

**Pull request merged**
