### PR TITLE
Removed 3 unused if conditions from ODIN's partial_map.cpp.

### PR DESCRIPTION
**Pull request by alirezazd**
I found 3 unused if statements in ODIN's partial_map.cpp which they were never executed and removed them from the source.
#### Types of changes

- [x] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by alirezazd** [comment]
@sdamghan

**Comment by sdamghan** [comment]
@alirezazd - LGTM, Thanks! Can you please update your branch with the master branch and squash all commits into one commit? Then it will be ready to merge into the master branch.

**Comment by sdamghan** [comment]
@alirezazd - LGTM, Thanks! Can you please update your branch with the master branch and squash all commits into one commit? Then it will be ready to merge into the master branch.

**Comment by alirezazd** [comment]
@sdamghan Done.

**Pull request merged**
