### PR TITLE
Build on M1

### PR DESCRIPTION
**Pull request by meme**
This allows vpr to be built on M1 MacBooks

#### Description

For this to work, you need `tbb@2020` from Homebrew.

I was able to build the software using this CMake command:

    TBBROOT=$(brew --prefix)/opt/tbb@2020/ cmake -DCMAKE_BUILD_TYPE=Release -DVPR_USE_EZGL=OFF -G Ninja -S . -B build

#### Types of changes

- [x] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by vaughnbetz** [comment]
Thanks for the contribution.
The changes look OK to me, and I've started CI.
@duck2 : there are some tbb build changes here to be compatible with apple.  I know you're also planning some changes to update our tbb version; could you take a look at these build changes and see if they interact with your update or if you have any thoughts.

**Comment by vaughnbetz** [comment]
Not sure why vtr_reg_nightly_test1 was cancelled; appeared everything in it passed already anyway.

**Comment by meme** [comment]
> Not sure why vtr_reg_nightly_test1 was cancelled; appeared everything in it passed already anyway.

It looks like it was cancelled because it hit the maximum timeout of 360 minutes. Not sure if that's related to my changes or not?

**Comment by duck2** [comment]
The current `FindTBB.cmake` doesn't work with newer TBB versions anyway, so it should be OK to hack on it. The rest of the changes look good to me as well

**Review by duck2 — APPROVED** [review]

**Comment by vaughnbetz** [comment]
Thanks.  Can't think of a reason why these changes would make us hit the 360 minute timeout (esp. after everything was done) so I'm assuming that was some transient infrastructure or load issue.  Merging.

**Pull request merged**
