### PR TITLE
Vpr noc output

### PR DESCRIPTION
**Pull request by Meet-Patel2580**
Updating NoC usage output message format

#### Description
 Updated the NoC usage output messages to organize the data into a table for better visual appeal and intuitiveness

#### Motivation and Context
Makes it easier for users to view the information when it is organized 

#### Types of changes

- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by vaughnbetz** [comment]
Please add an example output so we can look at.

**Comment by Meet-Patel2580** [comment]
> Here is an example of the updated output (table) compared to the original output.

Screenshot 2023-06-07 at 3 12 11 PM

Screenshot 2023-06-07 at 3 13 21 PM

**Review by saaramahmoudi — APPROVED** [review]
The code change looks fine. Thanks!

**Comment by vaughnbetz** [comment]
Looks good. A few suggested tweaks:
Title: I'd change to "Placement perturbation distribution by block and move type"
Percentage(%) --> % of Total
Acceptance -> Accepted
Rejection -> Rejected

**Comment by Meet-Patel2580** [comment]
Updated output table with suggested changes:
Screenshot 2023-06-07 at 6 27 10 PM

**Comment by Meet-Patel2580** [comment]
Ready to be merged. @vaughnbetz

**Pull request merged**
