### PR TITLE
Deploy new node.side() API to rr_graph builder and router

### PR DESCRIPTION
**Pull request by tangxifan**
This PR aims to deploy the new node_side() API to rr_graph builder and router.

#### Description

This PR:
- [X] Replace all the node.side() API with node.is_node_on_specific_side() API in rr_graph builder and router.
- [ ] Patch routers' lookahead map building for multi-width and multi-height blocks. This will be patched in later pull requests, because key roadblocks have been identified: require prev_node list to be cached for each rr_node so that lookahead builder can know accurate positions for SINK nodes.

#### Related Issue

To address issue #1580

#### Motivation and Context

In Titan architecture, a ``rr_node`` may appear in multiple sides of a logic block. However, VPR's rr_graph builder and router only assumes that a ``rr_node`` locates on only 1 side. There has been patches (#1621 and #1661) to extend the side support for ``rr_node`` and deploy to GUIs. This PR is a follow-up PR as planned to deploy the new API node.is_node_on_specific_side() in place of the to-be-deprecated API node_side() in the rr_graph builder and router.
After this PR, the old API can be safely removed.

#### Types of changes

- [X] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by tangxifan** [comment]
@litghost @vaughnbetz This PR is ready for your review.

**Comment by tangxifan** [comment]
According to the discussion, I have removed the compute-intensive coordinate adjustment in route lookahead builder. Instead, I use the first side for multi-side rr_nodes which does not impact any QoR on existing architectures. Patches may be required in case new architectures include multi-side rr_nodes which are widely spread on the perimeter of large blocks.

**Review by litghost — APPROVED** [review]
LGTM, CI is red though?

**Comment by tangxifan** [comment]
@litghost Just checked the CI on current master. The VTR nightly test remains red.

**Comment by vaughnbetz** [comment]
Failures are the same arm_core and one titan qor failure (17 failures, all recurring).  I thought the new golden results were in by now, but perhaps not. Not real failures in any case.

**Comment by vaughnbetz** [comment]
LGTM. Merging.

**Pull request merged**
