### PR TITLE
Unify shebangs, make script files executable

### PR DESCRIPTION
**Pull request by timor**
#### Description
The motivation in this change is to make it easier to run under NixOS,
which does not support absolute paths.  Note that a part of the scripts is
already using the `#!/usr/bin/env ...` shebang, which correctly calls the
executable which is present in the user's environment.  This commit makes this
behavior consistent over all scripts.

Also, the executable flags were missing for part of the scripts.

#### Motivation and Context
In addition to making it easier to use under NixOS, this should give consistent behavior when users have different interpreter versions in their paths as compared to the system-wide installed ones.

#### How Has This Been Tested?
Tested by running the perl tests in the toplevel directory.

#### Types of changes

- [x] Bug fix (change which fixes an issue)
- [x]  New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by kmurray** [comment]
This mostly looks good to me (although I'll leave the ODIN comments to @jeanlego). The only exceptions are that files under:
* `abc/` and 
* `libs/EXTERNAL/`

shouldn't be modified (since they come from external sources via [subtrees](https://docs.verilogtorouting.org/en/latest/dev/developing/#external-subtrees) which we don't modify in VTR).

We'll also need CI to be passing, and likely re-base these changes on the latest master as well.

**Comment by jeanlego** [comment]
Lgtg here.

**Comment by timor** [comment]
I added a commit which reverts the changes in `abc/` and `/libs/EXTERNAL`.

Shall I squash that?

**Comment by kmurray** [comment]
> Shall I squash that?

Yep that sounds good. The revision history of this branch should show no modifications to `abc/` and `libs/EXTERNAL`.

**Comment by timor** [comment]
Done

**Comment by jeanlego** [comment]
It is good to merge on the Odin side

**Comment by kmurray** [comment]
Thanks!

**Pull request merged**
