### PR TITLE
Remove old perl scripts

### PR DESCRIPTION
**Pull request by jgoeders**
Remove old perl scripts that are no longer used by the VTR flow.

#### Motivation and Context
#1509 #1429 introduced new python scripts to replace the Pythons scripts.

#### Types of changes

- [x] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by vaughnbetz** [comment]
A couple of travis ci failures.  Looks like a few regtests are still trying to use the perl scripts which are being removed here. E.g. the NO_GRAPHICS tests:

The command "./.github/travis/build.sh" exited with 0.
0.01s$ travis_wait 30 ./run_reg_test.pl vtr_reg_basic -show_failures -j2
Still running (1 of 30): ./run_reg_test.pl vtr_reg_basic -show_failures -j2
The command ./run_reg_test.pl vtr_reg_basic -show_failures -j2 exited with 127.
Log:
/home/travis/.travis/functions: line 619: ./run_reg_test.pl: No such file or directory
/home/travis/.travis/functions: line 607:  6250 Terminated              travis_jigger "${!}" "${timeout}" "${cmd[@]}"
The command "travis_wait 30 ./run_reg_test.pl vtr_reg_basic -show_failures -j2" exited with 127.

**Comment by jgoeders** [comment]
Yes, fixed in #1553.

I'll continue working on making this PR green, then I'll leave it draft for a few weeks as we discussed.

**Comment by vaughnbetz** [comment]
No issues so far, and CI is green.  Leave draft for a while longer or merge now?

**Comment by jgoeders** [comment]
@vaughnbetz Sorry, didn't see your earlier message.  I think it's been a while now.  I'll merge it.

**Pull request merged**
