### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by stef9998**
#### Description

Just a typo.

#### Types of changes

- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by vaughnbetz** [comment]
Thanks!

**Comment by vaughnbetz** [comment]
Thanks!

**Comment by soheilshahrouz** [comment]
I merged master to this branch to see if the labeler trigger changes from pull_request to pull_request_target.

**Comment by vaughnbetz** [comment]
Thanks!

**Pull request merged**
