### PR TITLE
Replaced CRLFs with LFs

### PR DESCRIPTION
**Pull request by jhol**
#### Description
This pull requests replaces all CRLF line endings in source files within the repository, and 

#### Related Issue
#326

#### Motivation and Context
The presence of CRLFs scattered inconsistently across the source code makes correct text editor configuration error prone.

#### How Has This Been Tested?
Not appplicable

#### Types of changes

- [x] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by jhol** [comment]
@kmurray is it possible to expedite this PR? Every time more commits go into master, I have to rebuilt the patch-set.

**Comment by kmurray** [comment]
Thanks for the pull request!

I haven't had a chance to go through all the changes yet. I'll try and get comments back to you sometime today.

**Comment by kmurray** [comment]
Thanks for putting this together. Cleaning up line-endings and odd characters is definitely something which needs to be done.

However it looks like some of these changes effect code which is developed externally (e.g. abc) and included in VTR via git-subtree. We try not to avoid applying any local modifications to such files, ensuring we can easily update these dependencies in the future.

Would it be possible to exclude these locations (listed below) from these changes?
- `abc`
- `libs/EXTERNAL`

Everything else should be fair game, as it is code we are responsible for.

**Comment by jhol** [comment]
@kmurray Ok, I rebuilt the patch set again with the following changes:

* Excluded `abc` and `libs/EXTERNAL`. It turns out that not modification was made to these file. However, many files in `abc_with_bb_support` were modified previously, and are no longer in the new version of the patch-set.
* Removed trailing whitespace on each lines from C/C++ source files.

**Comment by kmurray** [comment]
@jhol Thanks!

However it still looks like there are a couple of changes which are touching files under `abc` or `libs/EXTERNAL`:

- eb47460: Changes a couple files under `abc`
- 8f9475a: Changes a number of files under `libs/EXTERNAL/`

If we can drop those modifications it should be good to merge.

**Comment by jhol** [comment]
@kmurray you're right. fixed it now and rebuilt it on top of master

**Comment by kmurray** [comment]
Thanks again for putting this together!

**Pull request merged**
