### PR TITLE
Python linting

### PR DESCRIPTION
**Pull request by jgoeders**
Add python lint checking, requiring that new Python files pass pylint checking.

#### Description
Added a script, `dev/pylint_check.py` which calls the `pylint` python linter on python files in specified directories.

Currently it is configured to locate all python files in the following directories (recursively), subject to feedback in this pull request.
  * `dev`
  * `ODIN_II`
  * `ace2`
  * `doc`
  * `vpr`
  * `vtr_flow`

The new script includes a list of all existing Python files in these directories that fail linting, and these files will be "grandfathered" in, meaning they do not need to pass linting at the moment. However, in the future we would ideally clean up these files so that they pass linting.

A travis CI test is added that ensures this script passes, meaning no (non-grandfathered) python files fail linting.  This will ensure all future Python files added to the repo pass linting.

`pylint` is highly configurable.  Currently, it is running under default configuration (no checks are skipped).  In the future, if we feel some checks are unwarranted, we could modify the configuration.

#### Related Issue
#1434 

#### Motivation and Context
Since we are about to move the core scripts to Python (#1429), it makes sense to set this in place now. 

#### How Has This Been Tested?
New Travis CI test, and lint testing on the new script added in this PR.

#### Types of changes

- [ ] Bug fix (change which fixes an issue)
- [x] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [x] My change requires a change to the documentation
- [x] I have updated the documentation accordingly
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by jgoeders** [comment]
@jeanlego Do you want this applied to ODIN or not?

**Comment by jeanlego** [comment]
> @jeanlego Do you want this applied to ODIN or not?

would love to see this applied on ODIN!

thanks :)

**Comment by vaughnbetz** [comment]
Looks good to me -- this is a good change.  Thanks.

**Comment by jgoeders** [comment]
Fixes #1434

**Pull request merged**
