### PR TITLE
fix #2089 Cluster attraction groups for tight floorplan constraints n…

### LINKED ISSUE #2089: Cluster attraction groups for tight floorplan constraints not working
The merge of Mohamed Elgammal's new clustering api and refactoring somehow broke cluster attraction groups, which are necessary for tight floorplan region constraints. They should be fixed.

#### Expected Behaviour
Attraction groups should force a dense packing on parts of a design with tight floorplan constraints.

#### Current Behaviour
Instead, sfkhalid tells me that they currently don't work (in fact area seems to increase in later clustering attempts) so something is broken.  

#### Possible Solution
These did work, so presumably something was broken in the refactoring. 

#### Steps to Reproduce
I believe the failures happen on the tests Sarah has on her own branch, but which aren't yet on master.

#### Context
Need this fixed before recommending people use the floorplan constraints. This is also holding up putting a full set of tests for floorplanning into CI, which is dangerous as more things could break without anyone knowing.

#### Your Environment
VTR master in late May, Linux

### PR DESCRIPTION
**Pull request by zhaisitong**
This PR recovers the dense packing on parts of a design with tight floorplan constraints. The relevant codes work until Jun 8 d22193d4c8030a24daa73884b60d9bdb8d0aec0b. But the reason is missing the condition "if (cur_pb→pb_stats→num_feasible_blocks == 0)" when finding unpacked molecules based on attraction group of the current cluster.

#### Description

In function  cluster_util.cpp: get_highest_gain_molecule, add the condition "if (cur_pb→pb_stats→num_feasible_blocks == 0)" before finding unpacked molecules based on attraction group.

#### Related Issue

The issue is #2089 .

#### Motivation and Context

This issue causes the failure to work on the design with tight floorplan constraints.

#### How Has This Been Tested?

The failed three testcases mentioned in #2089 work after adding the "num_feasible_blocks == 0" condition.

#### Types of changes

- [x] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by vaughnbetz** [comment]
@zhaisitong : @MohamedElgammal refactored the clustering code to make cluster.cpp smaller --> I think your commit has undone that, which isn't desirable.  Can you look deeper into the changes to see what has gone wrong?

Also, I'm not sure why this PR is closed -- seems CI didn't fully pass and it isn't merged to master?  In any case, we shouldn't merge this to master as it will undo a bunch of desirable changes.

**Comment by zhaisitong** [comment]
This problem has been solved for issue #2089 .

**Comment by vaughnbetz** [comment]
Thanks @zhaisitong .  
1. Can you describe the testing you did to confirm the issue is gone?
2. Can you add CI tests (regression tests) to ensure this continues to work?  I think the commands Mohamed/Sarah sent earlier should work as regression tests if you check them in.  The procedure to add tests to CI is documented at https://docs.verilogtorouting.org/en/latest/README.developers/#adding-tests

**Comment by zhaisitong** [comment]
@vaughnbetz 
1. I tested the three commands Mohamed gave me in #2089, and passed all 74 checks.
2. The architecture name is the same with the architecture "strarixiv_arch.timing.xml" in our vtr_flow/arch/tian, but  Mohamed gave another specified device size layout in the architecture file. How to treat this architecture file? Could I rename it and upload to the path "vtr_flow/arch/titan" ?

**Comment by vaughnbetz** [comment]
Thanks @zhaisitong .  I think renaming the architecture file (with something meaningful, like stratixiv_arch_timing_fixed_size.xml) and uploading it should be fine. Adding @MohamedElgammal in case he wants to comment.

**Comment by vaughnbetz** [comment]
Merging this fix; @zhaisitong will add the CI tests in a separate PR.

**Pull request merged**
