### PR TITLE
Gitpod configuration

### PR DESCRIPTION
**Pull request by sdamghan**
#### Description

1. The origin remote of the repository in Gitpod was the Loksu fork -> changed to the main VTR repo
2. Running tasks in the `gitpod.yml` caused errors at the starting point of the Gitpod -> removed
3. Setting the working directory for the docker file as VTR_ROOT env.

#### Motivation and Context

wrong URL and removing errors

#### Types of changes

- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by sdamghan** [comment]
@mithro the GitPod is a pretty cool tool, thanks for introducing it. I've just made a couple of changes, please let me know your thoughts.

**Comment by mithro** [comment]
LGTM!

We should be testing in CI that GitPod is working in some way?

**Comment by sdamghan** [comment]
We need to install GitPod ([link](https://github.com/apps/gitpod-io)) on the VTR repo. Afterwards, with changes in this Pr we should see a GitPod record to PR checks, like below:
SS


Link to above PR: https://github.com/sdamghan/gitpod/pull/1
Link to install GitPod guide: https://www.gitpod.io/docs/prebuilds/#configure-the-github-app

**Comment by mithro** [comment]
I have configured the GitPod GitHub App as requested.

**Review by mithro — APPROVED** [review]
LGTM.

**Pull request merged**
