### PR TITLE
Use std::string::find(char c) when searching for a single character.

### PR DESCRIPTION
**Pull request by hzeller**
Faster, and also clearer states intention.

Signed-off-by: Henner Zeller <h.zeller@acm.org>

#### Description
Very small cleanup.

### CODE REVIEW

**Comment by vaughnbetz** [comment]
Thanks.  Travis CI is a bit messed up right now; doing a kokoro force to run the remaining regtests on it. This looks very safe in any case.

**Comment by hzeller** [comment]
Uh, the CI is crunching on this three line change for over a month now ...

**Comment by vaughnbetz** [comment]
Sorry, the move away from travis caused some slowdown.  Updated to the latest, and the tests have restarted.  These should pass (and if irrelevant things fail I'll override to merge).

**Comment by hzeller** [comment]
Wonderful, looks like the test restart did work!

**Comment by vaughnbetz** [comment]
:).

**Pull request merged**
