### PR TITLE
Wirelength Estimation is printed after placement

### PR DESCRIPTION
**Pull request by saaramahmoudi**
#### Description
Wirelength estimation after placement was removed from vpr report.

#### Types of changes

- [x] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My change requires a change to the documentation
- [x] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by saaramahmoudi** [comment]
@vaughnbetz

**Comment by vaughnbetz** [comment]
Looks like everything worked except vtr_nightly_test1 timed out while packing up the results files (looks like that took over 2 hours, which is too long).  Re-launching it.
All the build tests seem to have worked (clang, gcc-8, etc.) but the overall B: Building VtR is marked waiting for status to be reported (not sure why).
@saaramahmoudi : please file an issue on the long file packing time and we can discuss it in the google meeting today ... we should find an owner for determining what the big files are and getting rid of them.
Relaunching the failed test on this PR to see if it will go through now.

**Comment by vaughnbetz** [comment]
Code change looks fine; will merge after the final test passes, or even if it times out again.

**Comment by saaramahmoudi** [comment]
@vaughnbetz nightly_test1 passed in the latest try.

**Pull request merged**
