### PR TITLE
Use Simple Place Delay Model By Default

### PR DESCRIPTION
**Pull request by amin1377**
In this PR, the default place delay mode is changed from `delt` (which runs the router for each `dx` and `dy` and stores the minimum cost across sample locations) to `simple` (which gets the minimum cost for each `dx` and `dy` from the information stored in the router lookahead).

### CODE REVIEW

**Comment by amin1377** [comment]
VTR Large: 
image

**Comment by amin1377** [comment]
Titan:
screenshot_2024-06-06_092317

**Comment by amin1377** [comment]
QoR on **all** koios circuits:
image

**Comment by vaughnbetz** [comment]
QoR data for Koios is actually for the placement refactoring ... ignore for this PR.

**Comment by vaughnbetz** [comment]
@amin1377 : is this good to merge (still a few CI failures)? @nedsels will benefit from the larger QoR tolerances in another PR.

**Pull request merged**
