### PR TITLE
Saving Graphics Feature

### PR DESCRIPTION
**Pull request by tinayang3024**
#### Description

- add command line option to save graphics into pdf output
  - generate outputs without getting into the event loop (popping up the window)
- add a button to save graphics
  - pop up a window asking for output file name and output file type (pdf, png, or svg)

#### Types of changes

- [ ] Bug fix (change which fixes an issue)
- [x] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by tinayang3024** [comment]
I am not sure why it keeps saying that I have conflicts, I did merge master into this branch...?

**Comment by kmurray** [comment]
This looks great! Just a couple of comments:

**Save Dialog Box**
image

1. The save dialog box doesn't describe that the drop down menu is for file types. It would be good to have some text like 'file format:' in the dialog box to make it clear what the drop down is for.

2. By default no file format is selected, so if you click save the program segfaults. Probably we should just pick a default (e.g. PDF).

3. The file name saved is strictly as entered, so if the user enters 'my_image' the file is saved as 'my_image' without any extension (regardless of the format selected). It may be less confusing to users to append the standard extension to what they enter. For instance, if they enter 'my_image' and select PDF as the format the file would save as 'my_image.pdf'.

**--save_graphics Option**

1. The graphics files seem to only be saved when both `--save_graphis on` _and_ `--disp on` are specified. This is somewhat conterintuitive, since when both are specified the graphics window doesn't actually pop up. Would it be possible to have `--save_graphics` operate independently of `--disp`? That way --disp would control whether the graphics window pops up, and --save_graphics controls whether the PDF files are generated.

2. The saved files seem to be lacking a file extension. I see the files 'vpr_placement' and 'vpr_routing' which are missing the .pdf file extension.

**Comment by tinayang3024** [comment]
I am done with fixing all of these points, I am not sure why the regression tests failed...

**Comment by kmurray** [comment]
Thanks @tinayang3024. I'm looking into the regression test failure but it should be unrelated to this change.

**Pull request merged**
