### PR TITLE
sdcparser: enable more symbols and allow symbol as start of a STR

### PR DESCRIPTION
**Pull request by acomodi**
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>

#### Description

This is to enhance the `libsdcparse` library to be able to parse additional symbols.
This is to include changes that happened in the EXTERNAL library: https://github.com/kmurray/libsdcparse/pull/3

#### Types of changes

- [ ] Bug fix (change which fixes an issue)
- [x] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by kmurray** [comment]
Thanks @acomodi. I was wondering how you updated this? 

Since this is [included in VTR via a subtree](https://docs.verilogtorouting.org/en/latest/dev/developing/#external-subtrees), the usual way to update it is with the `dev/external_subtrees.py` script.

**Comment by acomodi** [comment]
@kmurray Sure, wasn't sure how to deal with this, will fix it ASAP. thanks

**Comment by acomodi** [comment]
@kmurray Should be ok now, I have used the subtree update tool as suggested.

**Comment by kmurray** [comment]
Not sure why this is showing merge conflicts, but I merged this change via #1106.

**Pull request closed without merging**
