### PR TITLE
rr_graph: write pin name in addition to index

### PR DESCRIPTION
**Pull request by mcmasterg**
Add additional metadata to rr_graph <pin_class> entries to make manipulating rr_graphs easier outside VPR.

I've taken @mithro's changes towards this and made some minor cleanup for this PR (commit description, minor formatting, drop unrelated changes)

#### Description

rr_graph_writer.cpp was modified to output this new format with corresponding changes in rr_graph_reader.cpp

#### Related Issue

This supports work in the symbiflow-arch-defs repo towards importing ice40 routing, which cannot be represented by the arch.xml format

#### Motivation and Context

Currently rr_graph exports pin classes like this:

    <pin_class type="INPUT">0</pin_class>

Where the 0 index comes from a std::map internal to vpr. It is very difficult for external applications to predict how these indices are assigned to determine the original pin names.

@mithro proposed this should be written instead like:

    <pin_class type="INPUT">
    <pin index="0" ptc="2">bt.outpad[3]</pin>
    </pin_class>

Which is now very explicit in both name and indexing

#### How Has This Been Tested?

"./run_reg_test.pl vtr_reg_basic vtr_reg_strong" passes, which includes an rr_graph test. I also ran some tests against the symbiflow-arch-defs repo

#### Types of changes

- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

This is a breaking change to the rr_graph format, although I'm not under the impression its under widespread use

#### Checklist:

- [X] My change requires a change to the documentation
- [x] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [X] All new and existing tests passed

### CODE REVIEW

**Comment by mithro** [comment]
This looks good to me! You'll have to wait @kmurray 's review before you can submit however.

**Comment by kmurray** [comment]
It seems like the proposed format still requires the index to be specified. For instance, in the current format I get:
```xml
		<block_type id="2" name="clb" width="1" height="1">
			<pin_class type="INPUT">0 1 2 3 4 5 6 7 8 9 10 11 12 </pin_class>
			<pin_class type="INPUT">13 14 15 16 17 18 19 20 21 22 23 24 25 </pin_class>
			<pin_class type="INPUT">26 27 28 29 30 31 32 33 34 35 36 37 38 </pin_class>
			<pin_class type="INPUT">39 40 41 42 43 44 45 46 47 48 49 50 51 </pin_class>
			<pin_class type="INPUT">52 </pin_class>
			<pin_class type="OUTPUT">53 </pin_class>
			<pin_class type="OUTPUT">54 </pin_class>
			<pin_class type="OUTPUT">55 </pin_class>
			<pin_class type="OUTPUT">56 </pin_class>
			<pin_class type="OUTPUT">57 </pin_class>
			<pin_class type="OUTPUT">58 </pin_class>
			<pin_class type="OUTPUT">59 </pin_class>
			<pin_class type="OUTPUT">60 </pin_class>
			<pin_class type="OUTPUT">61 </pin_class>
			<pin_class type="OUTPUT">62 </pin_class>
			<pin_class type="OUTPUT">63 </pin_class>
			<pin_class type="OUTPUT">64 </pin_class>
			<pin_class type="OUTPUT">65 </pin_class>
			<pin_class type="OUTPUT">66 </pin_class>
			<pin_class type="OUTPUT">67 </pin_class>
			<pin_class type="OUTPUT">68 </pin_class>
			<pin_class type="OUTPUT">69 </pin_class>
			<pin_class type="OUTPUT">70 </pin_class>
			<pin_class type="OUTPUT">71 </pin_class>
			<pin_class type="OUTPUT">72 </pin_class>
			<pin_class type="OUTPUT">73 </pin_class>
			<pin_class type="INPUT">74 </pin_class>
		</block_type>
```

While in the proposed format I get:
```xml
		<block_type id="2" name="clb" width="1" height="1">
			<pin_class type="INPUT">
				<pin index="0" ptc="0">clb.I1[0]</pin>
				<pin index="1" ptc="1">clb.I1[1]</pin>
				<pin index="2" ptc="2">clb.I1[2]</pin>
				<pin index="3" ptc="3">clb.I1[3]</pin>
				<pin index="4" ptc="4">clb.I1[4]</pin>
				<pin index="5" ptc="5">clb.I1[5]</pin>
				<pin index="6" ptc="6">clb.I1[6]</pin>
				<pin index="7" ptc="7">clb.I1[7]</pin>
				<pin index="8" ptc="8">clb.I1[8]</pin>
				<pin index="9" ptc="9">clb.I1[9]</pin>
				<pin index="10" ptc="10">clb.I1[10]</pin>
				<pin index="11" ptc="11">clb.I1[11]</pin>
				<pin index="12" ptc="12">clb.I1[12]</pin>
			</pin_class>
			<pin_class type="INPUT">
				<pin index="0" ptc="13">clb.I2[0]</pin>
				<pin index="1" ptc="14">clb.I2[1]</pin>
				<pin index="2" ptc="15">clb.I2[2]</pin>
				<pin index="3" ptc="16">clb.I2[3]</pin>
				<pin index="4" ptc="17">clb.I2[4]</pin>
				<pin index="5" ptc="18">clb.I2[5]</pin>
				<pin index="6" ptc="19">clb.I2[6]</pin>
				<pin index="7" ptc="20">clb.I2[7]</pin>
				<pin index="8" ptc="21">clb.I2[8]</pin>
				<pin index="9" ptc="22">clb.I2[9]</pin>
				<pin index="10" ptc="23">clb.I2[10]</pin>
				<pin index="11" ptc="24">clb.I2[11]</pin>
				<pin index="12" ptc="25">clb.I2[12]</pin>
			</pin_class>
			<pin_class type="INPUT">
				<pin index="0" ptc="26">clb.I3[0]</pin>
				<pin index="1" ptc="27">clb.I3[1]</pin>
				<pin index="2" ptc="28">clb.I3[2]</pin>
				<pin index="3" ptc="29">clb.I3[3]</pin>
				<pin index="4" ptc="30">clb.I3[4]</pin>
				<pin index="5" ptc="31">clb.I3[5]</pin>
				<pin index="6" ptc="32">clb.I3[6]</pin>
				<pin index="7" ptc="33">clb.I3[7]</pin>
				<pin index="8" ptc="34">clb.I3[8]</pin>
				<pin index="9" ptc="35">clb.I3[9]</pin>
				<pin index="10" ptc="36">clb.I3[10]</pin>
				<pin index="11" ptc="37">clb.I3[11]</pin>
				<pin index="12" ptc="38">clb.I3[12]</pin>
			</pin_class>
			<pin_class type="INPUT">
				<pin index="0" ptc="39">clb.I4[0]</pin>
				<pin index="1" ptc="40">clb.I4[1]</pin>
				<pin index="2" ptc="41">clb.I4[2]</pin>
				<pin index="3" ptc="42">clb.I4[3]</pin>
				<pin index="4" ptc="43">clb.I4[4]</pin>
				<pin index="5" ptc="44">clb.I4[5]</pin>
				<pin index="6" ptc="45">clb.I4[6]</pin>
				<pin index="7" ptc="46">clb.I4[7]</pin>
				<pin index="8" ptc="47">clb.I4[8]</pin>
				<pin index="9" ptc="48">clb.I4[9]</pin>
				<pin index="10" ptc="49">clb.I4[10]</pin>
				<pin index="11" ptc="50">clb.I4[11]</pin>
				<pin index="12" ptc="51">clb.I4[12]</pin>
			</pin_class>
```
Where the `ptc` attribute in the proposed format corresponds to the contents of `<pin_class>` in the current format.

Doesn't this that mean whoever writes the rr_graph.xml still needs to figure out how VPR assigned the indices/ptcs (which what I understood to be the problem)? Or am I missing something?

**Comment by mithro** [comment]
I'm not sure I fully understand your comment yet. Hopefully the following explanation helps and @mcmasterg will probably reply a bit later too.

For our purposes, we need is a way to map between the "fully qualified" pin name, IE `tilename.portname[pinindex]` and the values used in the rr_nodes `ptc` property of the `SOURCE`/`SINK`/`IPIN`/`OPIN` nodes (found on the `loc` tag).

It was my understanding that the `ptc` property on `IPIN` and `OPIN` rr_nodes is the index of a pin at the block level?

It is also my understanding that when you have `equivalent=false` on a port, each pin will end up in it's own pin class. Therefore there is **not** a 1:1 mapping between ports and `pin_class` tags.

Is my understanding correct?

Thanks!

**Comment by mcmasterg** [comment]
@mithro I think what hes commenting on is this check

    auto num = get_attribute(pin, "ptc", loc_data).as_uint();
    if (num != class_inf.pinlist[index]) {
        vpr_throw(VPR_ERROR_OTHER, __FILE__, __LINE__,
              "Architecture file does not match RR graph's block pin list");
    }

The issue is that its expecting specific ptc values instead of taking them as the new values. Therefore in the current form you'd be able to munge the values, but you wouldn't be able to create an rr_graph from scratch

@kmurray From what I can tell this could be changed in VPR internally at a later date without changing the XML format. Is your preference to not merge this in unless it handles this case as well? For our current purposes we are okay munging the generated rr_graph, but I agree long term this will have to be fixed.

**Comment by kmurray** [comment]
> It was my understanding that the ptc property on IPIN and OPIN rr_nodes is the index of a pin at the block level?

@mithro That is correct

> It is also my understanding that when you have equivalent=false on a port, each pin will end up in it's own pin class. Therefore there is not a 1:1 mapping between ports and pin_class tags.

@mithro Also correct


> Therefore in the current form you'd be able to munge the values, but you wouldn't be able to create an rr_graph from scratch

@mcmasterg OK that makes sense. It was just my impression that was what this PR was trying to resolve :)

> Is your preference to not merge this in unless it handles this case as well? For our current purposes we are okay munging the generated rr_graph, but I agree long term this will have to be fixed.

@mcmasterg You folks are the main customers for this, so if you're happy with adding the ability to write an RR graph from scratch at a later date it is OK with me.

**Comment by kmurray** [comment]
**Pin Class Index**
Now that I understand what this PR is trying to do I do have one comment.

Conceptually, a pin class is a _set_ of equivalent pins, so it doesn't really matter what order they are specified in.

I _think_ that means we can just drop the `index` attribute so:
```xml
<pin_class type="INPUT">
				<pin index="0" ptc="0">clb.I1[0]</pin>
				<pin index="1" ptc="1">clb.I1[1]</pin>
</pin_class>
```

would become:
```xml
<pin_class type="INPUT">
				<pin ptc="0">clb.I1[0]</pin>
				<pin ptc="1">clb.I1[1]</pin>
</pin_class>
```
which seems clearer and more straight forward (and in-line with removing `index` references as in #322).

The santiy checks in rr_graph_reader.cpp would only need to be updated to use `std::find` (or similar) on `class_inf.pinlist` based on the `ptc`, instead of relying directly on the `index` attribute.

With this change (unless there are other thoughts on it), I'd be happy to merge this.

**Comment by mithro** [comment]
@mcmasterg Ping?

**Pull request merged**
