### PR TITLE
Moving COFFE 22nm architectures from arch/timing to arch/COFFE_22nm

### PR DESCRIPTION
**Pull request by aman26kbm**
Moving COFFE 22nm architectures from arch/timing to arch/COFFE_22nm

#### Description

1. Moving 22nm architectures generated by using COFFE to a new
location (arch/COFFE_22nm). This shouldn't change anything functionally.
This is being done purely for organizational purposes.

2. Updating the paths to arch files in the task file files, for
the architectures that have moved to COFFE_20nm directory.

3. Updating comments about how the delays and areas in some
architectures were obtained (obtained from email conversations with Vaugh B. and Mohamed E.)

#### Related Issue

No issue exists. This was discussed in email threads with @vaughnbetz 

#### Motivation and Context

This is being done for purely organizational purposes. No functional difference.

#### How Has This Been Tested?

Ran vtr_reg_basic and vtr_reg_strong test suites. All tests passed.

#### Types of changes

- [ ] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
None of the above.

#### Checklist:

- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by aman26kbm** [comment]
@vaughnbetz , please review.

**Comment by vaughnbetz** [comment]
Thanks Aman.  Looks good.  Tests should be fine, just waiting for them to go green.  I'm doing a force restart on kokoro since one the strong tests seem to be stuck.

**Comment by aman26kbm** [comment]
@vaughnbetz , can this be merged and closed?

**Comment by aman26kbm** [comment]
Thanks, @vaughnbetz

**Pull request merged**
