### PR TITLE
Support packing when modes provide different routing

### PR DESCRIPTION
**Pull request by mithro**
This is a work in progress. I'm sending it to get feedback on the change.

This makes the packer work when there are multiple modes which change the routing pattern through a cluster.

The packer will try and pack everything together, then it will fail routing causing it to fall back to checking routing atom-by-atom.

This will then cause the packer to not add the conflicting modes into one cluster.

### CODE REVIEW

**Comment by mithro** [comment]
@kmurray I've now fixed it so that in the case of no routing conflicts the speed should be pretty much identical. I guess I just need to add a test here now?

**Comment by mithro** [comment]
This seems to cause failures at the moment;
```
Test 'vtr_reg_strong' had 30 qor test failures
Test 'vtr_reg_strong' had 1 run failures
Test complete
Error: 31 tests failed!
```

```
regression_tests/vtr_reg_strong/strong_fracturable_luts...
[Fail]  k6_N8_I80_fleI10_fleO2_ff2_nmodes_2.xml/ch_intrinsics.v/common vpr_status: golden = success result = exited with return code 1
[Fail]  k6_N8_I80_fleI10_fleO2_ff2_nmodes_2.xml/ch_intrinsics.v/common num_post_packed_nets: golden = 249 result = -1
[Fail]  k6_N8_I80_fleI10_fleO2_ff2_nmodes_2.xml/ch_intrinsics.v/common device_width: golden = 11 result = -1
[Fail]  k6_N8_I80_fleI10_fleO2_ff2_nmodes_2.xml/ch_intrinsics.v/common device_height: golden = 11 result = -1
[Fail]  k6_N8_I80_fleI10_fleO2_ff2_nmodes_2.xml/ch_intrinsics.v/common min_chan_width: golden = 36 result = -1
[Fail]  k6_N8_I80_fleI10_fleO2_ff2_nmodes_2.xml/ch_intrinsics.v/common routed_wirelength: golden = 1599 result = -1
[Fail]  k6_N8_I80_fleI10_fleO2_ff2_nmodes_2.xml/ch_intrinsics.v/common logic_block_area_total: golden = 0 result = -1
[Fail]  k6_N8_I80_fleI10_fleO2_ff2_nmodes_2.xml/ch_intrinsics.v/common logic_block_area_used: golden = 0 result = -1
[Fail]  k6_N8_I80_fleI10_fleO2_ff2_nmodes_2.xml/ch_intrinsics.v/common min_chan_width_routing_area_total: golden = 316062. result = -1
[Fail]  k6_N8_I80_fleI10_fleO2_ff2_nmodes_2.xml/ch_intrinsics.v/common min_chan_width_routing_area_per_tile: golden = 2612.08 result = -1
[Fail]  k6_N8_I80_fleI10_fleO2_ff2_nmodes_2.xml/ch_intrinsics.v/common num_clb: golden = 14 result = -1
[Fail]  k6_N8_I80_fleI10_fleO2_ff2_nmodes_2.xml/ch_intrinsics.v/common num_io: golden = 99 result = -1
[Fail]  k6_N8_I80_fleI10_fleO2_ff2_nmodes_2.xml/ch_intrinsics.v/common num_outputs: golden = 130 result = -1
[Fail]  k6_N8_I80_fleI10_fleO2_ff2_nmodes_2.xml/ch_intrinsics.v/common num_memories: golden = 1 result = -1
[Fail]  k6_N8_I80_fleI10_fleO2_ff2_nmodes_2.xml/ch_intrinsics.v/common num_mult: golden = 0 result = -1
regression_tests/vtr_reg_strong/strong_mcnc...[Pass]
regression_tests/vtr_reg_strong/strong_no_timing...
[Fail]  k6_frac_N10_frac_chain_depop50_mem32K_40nm.xml/ch_intrinsics.v/common vpr_status: golden = success result = exited with return code 1
[Fail]  k6_frac_N10_frac_chain_depop50_mem32K_40nm.xml/ch_intrinsics.v/common num_post_packed_nets: golden = 250 result = -1
[Fail]  k6_frac_N10_frac_chain_depop50_mem32K_40nm.xml/ch_intrinsics.v/common device_width: golden = 10 result = -1
[Fail]  k6_frac_N10_frac_chain_depop50_mem32K_40nm.xml/ch_intrinsics.v/common device_height: golden = 10 result = -1
[Fail]  k6_frac_N10_frac_chain_depop50_mem32K_40nm.xml/ch_intrinsics.v/common min_chan_width: golden = 34 result = -1
[Fail]  k6_frac_N10_frac_chain_depop50_mem32K_40nm.xml/ch_intrinsics.v/common routed_wirelength: golden = 2330 result = -1
[Fail]  k6_frac_N10_frac_chain_depop50_mem32K_40nm.xml/ch_intrinsics.v/common logic_block_area_total: golden = 3.92691e+06 result = -1
[Fail]  k6_frac_N10_frac_chain_depop50_mem32K_40nm.xml/ch_intrinsics.v/common logic_block_area_used: golden = 1.08694e+06 result = -1
[Fail]  k6_frac_N10_frac_chain_depop50_mem32K_40nm.xml/ch_intrinsics.v/common min_chan_width_routing_area_total: golden = 218071. result = -1
[Fail]  k6_frac_N10_frac_chain_depop50_mem32K_40nm.xml/ch_intrinsics.v/common min_chan_width_routing_area_per_tile: golden = 2180.71 result = -1
[Fail]  k6_frac_N10_frac_chain_depop50_mem32K_40nm.xml/ch_intrinsics.v/common num_clb: golden = 10 result = -1
[Fail]  k6_frac_N10_frac_chain_depop50_mem32K_40nm.xml/ch_intrinsics.v/common num_io: golden = 99 result = -1
[Fail]  k6_frac_N10_frac_chain_depop50_mem32K_40nm.xml/ch_intrinsics.v/common num_outputs: golden = 130 result = -1
[Fail]  k6_frac_N10_frac_chain_depop50_mem32K_40nm.xml/ch_intrinsics.v/common num_memories: golden = 1 result = -1
[Fail]  k6_frac_N10_frac_chain_depop50_mem32K_40nm.xml/ch_intrinsics.v/common num_mult: golden = 0 result = -1
```

**Comment by kmurray** [comment]
```
Test 'vtr_reg_strong' had 1 run failures
```
Indicates that tests crashed or exited non-zero (likely shown as 'Fail' earlier in the log). The QoR failures are likely related to that (-1 is a default value).

**Comment by mithro** [comment]
This change now passes all the existing `vtr_reg_strong` tests and adds a new test to make sure that this feature continues to work.

**Comment by mithro** [comment]
@kmurray PTAL

**Comment by mithro** [comment]
@kmurray Ping?

**Pull request closed without merging**
